import {
  Card1,
  Card11,
  Card2,
  Card12,
  Card3,
  Card13,
  Card4,
  Card14,
  Card5,
  Card15,
  Card6,
  Card16,
} from "../../images";
const Data = [
  {
    title: "Introduction to user research in ux design",
    img: { Card1 },
    category: "Design",
    reviews: "4.7k",
    purchases: "32.7k+",
    time: "23hrs 500mins",
    lessons: "15",
    author: "Leonard Victor",
    price: "15.00",
    authorImg: { Card11 },
  },
  {
    title: "Introduction to  new marketing audience ",
    img: { Card2 },
    category: "Marketing",
    reviews: "4.7k",
    purchases: "8.7k+",
    time: "22hrs 30mins",
    lessons: "22",
    author: "Jeffrey Williams",
    price: "32.00",
    authorImg: { Card12 },
  },
  {
    title: "Introduction to html, css & bootstrap",
    img: { Card3 },
    category: "Development",
    reviews: "4.7k",
    purchases: "8.7k+",
    time: "22hrs 30mins",
    lessons: "22",
    author: "Claretta Mason",
    price: "55.00",
    authorImg: { Card13 },
  },
  {
    title: "Introduction to html, css & bootstrap",
    img: { Card4 },
    category: "Development",
    reviews: "4.7k",
    purchases: "8.7k+",
    time: "22hrs 30mins",
    lessons: "22",
    author: "Claretta Mason",
    price: "55.00",
    authorImg: { Card14 },
  },
  {
    title: "Introduction to html, css & bootstrap",
    img: { Card5 },
    category: "Marketing",
    reviews: "4.7k",
    purchases: "8.7k+",
    time: "22hrs 30mins",
    lessons: "22",
    author: "Claretta Mason",
    price: "55.00",
    authorImg: { Card15 },
  },
  {
    title: "Introduction to html, css & bootstrap",
    img: { Card6 },
    category: "Marketing",
    reviews: "4.7k",
    purchases: "8.7k+",
    time: "22hrs 30mins",
    lessons: "22",
    author: "Claretta Mason",
    price: "55.00",
    authorImg: { Card16 },
  },
];
export default Data;
